services:
  artifactory:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    working_dir: /workarea
    volumes:
      - .:/workarea:ro
    command:
      - python3.9
      - server.py

  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    depends_on:
      - artifactory
    command:
      - curl
      - http://artifactory
