services:
  artifactory:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    volumes:
      - .:/workarea:ro
    command:
      - python3.9
      - -m
      - flask
      - run

  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    depends_on:
      - artifactory
    command:
      - curl
      - artifactory
