networks:
  hermetic:
    internal: true

services:
  raw.githubusercontent.com:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    working_dir: /workarea
    volumes:
      - .:/workarea:ro
    networks:
      - hermetic
    command:
      - python3.9
      - server.py

  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    depends_on:
      - raw.githubusercontent.com
    networks:
      - hermetic
    command:
      - curl
      - -k
      - https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
